### ISSUE TITLE
The examples page doesnt work

### ISSUE THREAD

**Issue by gauravojha** [igorlino/angular-elevatezoom-plus#10]
On the examples page [http://igorlino.github.io/angular-elevatezoom-plus/#/examples], on clicking the show the code button, nothing seems to be happening.

**Comment by boarnoah** [comment]
You can try follow them along here: https://github.com/igorlino/elevatezoom-plus/tree/gh-pages/snippets, the ids of the imgs match the corresponding files.

**Comment by gauravojha** [comment]
@boarnoah  @igorlino 
Thanks. I did try that. But still nothing seems to be happening. I have a simple html and js attached below. The image is shown, but nothing happens on mouse hover.

Could you please help me once?

Code for html:
[a.txt](https://github.com/igorlino/angular-elevatezoom-plus/files/319998/a.txt)

**Comment by gauravojha** [comment]
Ok I got it. The script has to be after the image has been loaded. So including the script after the body tag works. 
But why is this done? What if the user includes all scripts on the top?
