### ISSUE TITLE
use semver for release versioning

### ISSUE THREAD

**Issue by akleiber** [igorlino/angular-elevatezoom-plus#12]
Hello,

thank you for your plugin. I really like it.
Your versioning with letters, i.e. 1.1.18d makes it unable to load the newest version without specifying it exactly. When using `1.1.*` bower will just install `1.1.18` and none of `1.1.18a`, `1.1.18b`etc.

Proposal: Use sematic versioning specified on http://semver.org/spec/v2.0.0.html

http://semver.org/spec/v2.0.0.html#spec-item-2
http://semver.org/spec/v2.0.0.html#spec-item-10

**Comment by igorlino** [comment]
makes sense. the only thing is that I'm try keeping the version of the ezp library on parity with the angular directive.

but thats easy to fix, I will make the ezp library use a more friendly version also.

**Comment by akleiber** [comment]
awesome, thank you :-)

**Comment by igorlino** [comment]
alright, its done. have fun. Any issues,  PR  are always welcome.

**Comment by akleiber** [comment]
really cool! thank you
