### ISSUE TITLE
How it-is works ?

### ISSUE THREAD

**Issue by lhadjadj** [igorlino/angular-elevatezoom-plus#17]
Hi, i use the elvevateZoom (jequerry), but in my new page i use angular and the plugin doesn't work. 
So i find your extension for the  jquery-ez-plus. Super. But it doesn't work anymore.  the documentation is too poor (for angularJS), the exemple are for jquery not for angularJS.
Please help-me

**Comment by igorlino** [comment]
Hi, yes they are working see:
http://igorlino.github.io/angular-elevatezoom-plus/#/examples

Documentation is also there

http://igorlino.github.io/angular-elevatezoom-plus/#/main
http://igorlino.github.io/angular-elevatezoom-plus/#/api

and of course looking at the demo source code

**Comment by igorlino** [comment]
ah, the source code of the demo you find at:

https://github.com/igorlino/angular-elevatezoom-plus/tree/gh-pages
