### ISSUE TITLE
Disable directive

### ISSUE THREAD

**Issue by juanchavezlive** [igorlino/angular-elevatezoom-plus#2]
Hello my friend
I was wondering if there is a way to disable the directive in base a binding.

**Comment by igorlino** [comment]
Hi, To understand you better I need an example.

If that would be possible how would it look like ?

**Comment by igorlino** [comment]
rephrasing, comparing to other angular directives, how would you like to disable it ?

Adding a wrapper <div ng-if="expression"></div> would definitively disable it.

**Comment by juanchavezlive** [comment]
I was thinking in a property that allow to enable or disable the directive like:

```
<img ez-plus ezp-model="{large:picture.fileNameUniqueWithPath}"  ezp-enabled="model.enableMagnifier">
```

But i didn't know that a wrapper could solve it.
