### ISSUE TITLE
Module setup instructions (ezPlus is not a function)

### ISSUE THREAD

**Issue by boarnoah** [igorlino/angular-elevatezoom-plus#9]
Having trouble getting this to initalize/work. For reference I am testing this out on [Barebones Angular](https://github.com/dwatling/barebones-angular/). 

Github markdown is very hard to work with so I've put it into a gist here: 
https://gist.github.com/boarnoah/720e50573fcd0e18f61d172ce65e0143

Steps 1-2 are what I understand the bare minimum needed to enable this plugin should be?
I also added in step 3 to help troubleshoot

Anyway the issue is that, for some reason I get the following error:
angular.js:11607TypeError: angular.element(...).ezPlus is not a function
    at preparePlugin (angular-ezplus.min.js:188)
    at Object.fn (angular-ezplus.min.js:147)
    at l.$digest (angular.js:14243)
    at l.$apply (angular.js:14506)
    at l (angular.js:9659)
    at P (angular.js:9849)
    at XMLHttpRequest.w.onload (angular.js:9790)

Have not been able to resolve it in anyway, any ideas?

EDIT: Just to clear up any confusion:
- I tried various versions of the plugin both locally and with rawgit
- Not sure why my inital tests broke in a different way unless I didn't include both jquery and jquery ez-plus. I've cleaned up and put in what I beleive is the minimum working code required here:
  https://github.com/boarnoah/barebones-angular/tree/ngezp  (please see the latest commit on that branch)

**Comment by boarnoah** [comment]
So the angularjs portion (this repo) needs the jquery-ezp portion (the actual module code) to function. Didn't understand from the instructions will create a PR to update the documentation later, unless you folks already have that in the works?

**Comment by igorlino** [comment]
@boarnoa sorry was too busy or away from computer. Please feel free contribute cleaner documentation updates. I'm always happy to see other developers improve the project.

**Comment by pradeep-rajapaksha** [comment]
![capture12](https://user-images.githubusercontent.com/10897784/32773876-9a7e2190-c950-11e7-85d9-c787983e0707.PNG)
I'm having this issue and no idea how to get fixed! please help!

**Comment by Hani-Ghazi** [comment]
@pradeep-rajapaksha  load the "jquery.ez-plus.js" file before the angularJs

**Comment by sabeehshah** [comment]
@Hani-Ghazi can you explain that a little bit more with regards to Angular 6, i have my jquery.ez-plus.js load after the normal jquery.js but its still not working, once i put the function call in console after page is loaded it works. Idk how to load the external js files at the beginning
